version: '3.8'

services:
  db:
     image: mariadb
     container_name: db
     restart: always
     env_file: .env
     environment:
       - MYSQL_DATABASE=my-db
       - MYSQL_DB_HOST=db:3306
       - MYSQL_DB_USER=$MYSQL_USER
       - MYSQL_DB_PASSWORD=$MYSQL_PASSWORD
     volumes:
       - dbdata:/var/lib/mysql
     command: '--default-authentication-plugin=mysql_native_password'
     networks:
       - app-network

  php:
     container_name: php
     image: php:7-fpm
     volumes:
       - ./src:/var/www/html
     networks:
       - app-network

  webserver:
     depends_on:
       - php
     image: nginx:1.19.6-alpine
     container_name: webserver
     restart: always
     ports:
       - "80:80"
     volumes:
       - ./src:/var/www/html
       - ./site.conf:/etc/nginx/conf.d/default.conf
     links: 
       - php
     networks:
       - app-network


volumes:
   dbdata:
   
networks:
   app-network:
     driver: bridge
